## This rule redirects to an external API, signing requests with a secret
[[redirects]]
  from = "https://antrikshmisri-legacy.netlify.app/"
  to = "http://portfolio-antriksh.herokuapp.com/"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
  signed = "API_SIGNATURE_TOKEN"
